version: '3'
services:
#Service sa toma el Dockerfile de ./laboratorio
 proxmox:
  build: ./proxmox
  hostname: proxmox
  privileged: true
  ports:
  - "8016:8006"
  volumes:
  - /sys/fs/cgroup:/sys/fs/cgroup:ro
